/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SmartScholarTuitionRouteImport } from './routes/smart-scholar-tuition'
import { Route as GurukulaAcademyRouteImport } from './routes/gurukula-academy'
import { Route as IndexRouteImport } from './routes/index'

const SmartScholarTuitionRoute = SmartScholarTuitionRouteImport.update({
  id: '/smart-scholar-tuition',
  path: '/smart-scholar-tuition',
  getParentRoute: () => rootRouteImport,
} as any)
const GurukulaAcademyRoute = GurukulaAcademyRouteImport.update({
  id: '/gurukula-academy',
  path: '/gurukula-academy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gurukula-academy': typeof GurukulaAcademyRoute
  '/smart-scholar-tuition': typeof SmartScholarTuitionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gurukula-academy': typeof GurukulaAcademyRoute
  '/smart-scholar-tuition': typeof SmartScholarTuitionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gurukula-academy': typeof GurukulaAcademyRoute
  '/smart-scholar-tuition': typeof SmartScholarTuitionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/gurukula-academy' | '/smart-scholar-tuition'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gurukula-academy' | '/smart-scholar-tuition'
  id: '__root__' | '/' | '/gurukula-academy' | '/smart-scholar-tuition'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GurukulaAcademyRoute: typeof GurukulaAcademyRoute
  SmartScholarTuitionRoute: typeof SmartScholarTuitionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/smart-scholar-tuition': {
      id: '/smart-scholar-tuition'
      path: '/smart-scholar-tuition'
      fullPath: '/smart-scholar-tuition'
      preLoaderRoute: typeof SmartScholarTuitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gurukula-academy': {
      id: '/gurukula-academy'
      path: '/gurukula-academy'
      fullPath: '/gurukula-academy'
      preLoaderRoute: typeof GurukulaAcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GurukulaAcademyRoute: GurukulaAcademyRoute,
  SmartScholarTuitionRoute: SmartScholarTuitionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
